// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/merchant.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterMerchantReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EntityName          string                 `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`                            // 商户主体名称，公司名称
	BrandName           string                 `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`                               // 商户品牌名称
	WebsiteUrl          string                 `protobuf:"bytes,3,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`                            // 商户官方网站
	MerchantLogo        string                 `protobuf:"bytes,4,opt,name=merchant_logo,json=merchantLogo,proto3" json:"merchant_logo,omitempty"`                      // 商户官方logo URL
	MerchantCountry     string                 `protobuf:"bytes,5,opt,name=merchant_country,json=merchantCountry,proto3" json:"merchant_country,omitempty"`             // 商户经营国家
	ContactName         string                 `protobuf:"bytes,6,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`                         // 商户主要联系人姓名
	ContactEmail        string                 `protobuf:"bytes,7,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`                      // 商户主要联系人邮箱
	BusinessDescription string                 `protobuf:"bytes,8,opt,name=business_description,json=businessDescription,proto3" json:"business_description,omitempty"` // 商户业务描述(可选)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterMerchantReq) Reset() {
	*x = RegisterMerchantReq{}
	mi := &file_proto_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMerchantReq) ProtoMessage() {}

func (x *RegisterMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMerchantReq.ProtoReflect.Descriptor instead.
func (*RegisterMerchantReq) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMerchantReq) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *RegisterMerchantReq) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *RegisterMerchantReq) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *RegisterMerchantReq) GetMerchantLogo() string {
	if x != nil {
		return x.MerchantLogo
	}
	return ""
}

func (x *RegisterMerchantReq) GetMerchantCountry() string {
	if x != nil {
		return x.MerchantCountry
	}
	return ""
}

func (x *RegisterMerchantReq) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *RegisterMerchantReq) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *RegisterMerchantReq) GetBusinessDescription() string {
	if x != nil {
		return x.BusinessDescription
	}
	return ""
}

type RegisterMerchantResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`             // 系统生成的商户ID
	ApiKey         string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                         // 系统生成的API密钥
	VerifiedStatus string                 `protobuf:"bytes,3,opt,name=verified_status,json=verifiedStatus,proto3" json:"verified_status,omitempty"` // 审核状态
	MerchantStatus string                 `protobuf:"bytes,4,opt,name=merchant_status,json=merchantStatus,proto3" json:"merchant_status,omitempty"` // 商户状态
	CreatedTime    string                 `protobuf:"bytes,5,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`          // 创建时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterMerchantResp) Reset() {
	*x = RegisterMerchantResp{}
	mi := &file_proto_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMerchantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMerchantResp) ProtoMessage() {}

func (x *RegisterMerchantResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMerchantResp.ProtoReflect.Descriptor instead.
func (*RegisterMerchantResp) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMerchantResp) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RegisterMerchantResp) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RegisterMerchantResp) GetVerifiedStatus() string {
	if x != nil {
		return x.VerifiedStatus
	}
	return ""
}

func (x *RegisterMerchantResp) GetMerchantStatus() string {
	if x != nil {
		return x.MerchantStatus
	}
	return ""
}

func (x *RegisterMerchantResp) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

var File_proto_merchant_proto protoreflect.FileDescriptor

const file_proto_merchant_proto_rawDesc = "" +
	"\n" +
	"\x14proto/merchant.proto\x12\x04card\"\xc1\x02\n" +
	"\x13RegisterMerchantReq\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x02 \x01(\tR\tbrandName\x12\x1f\n" +
	"\vwebsite_url\x18\x03 \x01(\tR\n" +
	"websiteUrl\x12#\n" +
	"\rmerchant_logo\x18\x04 \x01(\tR\fmerchantLogo\x12)\n" +
	"\x10merchant_country\x18\x05 \x01(\tR\x0fmerchantCountry\x12!\n" +
	"\fcontact_name\x18\x06 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_email\x18\a \x01(\tR\fcontactEmail\x121\n" +
	"\x14business_description\x18\b \x01(\tR\x13businessDescription\"\xc5\x01\n" +
	"\x14RegisterMerchantResp\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12'\n" +
	"\x0fverified_status\x18\x03 \x01(\tR\x0everifiedStatus\x12'\n" +
	"\x0fmerchant_status\x18\x04 \x01(\tR\x0emerchantStatus\x12!\n" +
	"\fcreated_time\x18\x05 \x01(\tR\vcreatedTime2\\\n" +
	"\x0fMerchantService\x12I\n" +
	"\x10RegisterMerchant\x12\x19.card.RegisterMerchantReq\x1a\x1a.card.RegisterMerchantRespB\fZ\n" +
	"./merchantb\x06proto3"

var (
	file_proto_merchant_proto_rawDescOnce sync.Once
	file_proto_merchant_proto_rawDescData []byte
)

func file_proto_merchant_proto_rawDescGZIP() []byte {
	file_proto_merchant_proto_rawDescOnce.Do(func() {
		file_proto_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_merchant_proto_rawDesc), len(file_proto_merchant_proto_rawDesc)))
	})
	return file_proto_merchant_proto_rawDescData
}

var file_proto_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_merchant_proto_goTypes = []any{
	(*RegisterMerchantReq)(nil),  // 0: card.RegisterMerchantReq
	(*RegisterMerchantResp)(nil), // 1: card.RegisterMerchantResp
}
var file_proto_merchant_proto_depIdxs = []int32{
	0, // 0: card.MerchantService.RegisterMerchant:input_type -> card.RegisterMerchantReq
	1, // 1: card.MerchantService.RegisterMerchant:output_type -> card.RegisterMerchantResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_merchant_proto_init() }
func file_proto_merchant_proto_init() {
	if File_proto_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_merchant_proto_rawDesc), len(file_proto_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_merchant_proto_goTypes,
		DependencyIndexes: file_proto_merchant_proto_depIdxs,
		MessageInfos:      file_proto_merchant_proto_msgTypes,
	}.Build()
	File_proto_merchant_proto = out.File
	file_proto_merchant_proto_goTypes = nil
	file_proto_merchant_proto_depIdxs = nil
}
