

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: pelago-card-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pelago_card
      MYSQL_USER: pelago_card
      MYSQL_PASSWORD: pelago123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:alpine
    container_name: pelago-card-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Etcd 服务发现
  etcd:
    image: bitnami/etcd:latest
    container_name: pelago-card-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/bitnami/etcd
    restart: unless-stopped

  # Jaeger 链路追踪
  jaeger:
    image: jaegertracing/all-in-one:1.45
    container_name: pelago-card-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "14268:14268"  # jaeger.thrift
      - "16686:16686"  # Web UI
      - "14250:14250"  # gRPC
    restart: unless-stopped



volumes:
  mysql_data:
  redis_data:
  etcd_data:

networks:
  default:
    name: pelago-network 