version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15
    container_name: pelago-card-postgres
    environment:
      POSTGRES_DB: pelago_card
      POSTGRES_USER: pelago_card
      POSTGRES_PASSWORD: pelago123
    ports:
      - "15432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:alpine
    container_name: pelago-card-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Consul 服务发现
  consul:
    image: consul:1.15
    container_name: pelago-card-consul
    ports:
      - "8500:8500"   # Consul UI/HTTP API
      - "8600:8600/udp" # DNS
    command: "agent -dev -client=0.0.0.0"
    restart: unless-stopped

  # Jaeger 链路追踪
  jaeger:
    image: jaegertracing/all-in-one:1.45
    container_name: pelago-card-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "14268:14268"  # jaeger.thrift
      - "16686:16686"  # Web UI
      - "14250:14250"  # gRPC
    restart: unless-stopped

volumes:
  pgsql_data:
  redis_data:

networks:
  pelago-network:
    driver: bridge