// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: merchant.proto

package server

import (
	"context"

	"pelago-card-backend/app/merchant/internal/logic"
	"pelago-card-backend/app/merchant/internal/svc"
	"pelago-card-backend/app/pb/merchant"
)

type MerchantServiceServer struct {
	svcCtx *svc.ServiceContext
	merchant.UnimplementedMerchantServiceServer
}

func NewMerchantServiceServer(svcCtx *svc.ServiceContext) *MerchantServiceServer {
	return &MerchantServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MerchantServiceServer) RegisterMerchant(ctx context.Context, in *merchant.RegisterMerchantReq) (*merchant.RegisterMerchantResp, error) {
	l := logic.NewRegisterMerchantLogic(ctx, s.svcCtx)
	return l.RegisterMerchant(in)
}
