// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	card "pelago-card-backend/portal/internal/handler/card"
	cardholder "pelago-card-backend/portal/internal/handler/cardholder"
	merchant "pelago-card-backend/portal/internal/handler/merchant"
	"pelago-card-backend/portal/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Logging, serverCtx.Prometheus},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/health",
					Handler: healthcheckHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// open card
				Method:  http.MethodPost,
				Path:    "/open",
				Handler: card.OpenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/card"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// cardholder register
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: cardholder.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/cardholder"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// merchant register
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: merchant.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/merchant"),
	)
}
