// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type GetMerchantReq struct {
	MerchantId string `path:"merchant_id" validate:"required"` // 商户ID
}

type GetMerchantResp struct {
	Merchant MerchantInfo `json:"merchant"` // 商户信息
}

type ListMerchantsReq struct {
	Page           int    `form:"page,default=1"`           // 页码，从1开始
	PageSize       int    `form:"page_size,default=10"`     // 每页大小
	VerifiedStatus string `form:"verified_status,optional"` // 筛选审核状态
	MerchantStatus string `form:"merchant_status,optional"` // 筛选商户状态
}

type ListMerchantsResp struct {
	Merchants []MerchantInfo `json:"merchants"` // 商户列表
	Total     int            `json:"total"`     // 总数量
	Page      int            `json:"page"`      // 当前页码
	PageSize  int            `json:"page_size"` // 每页大小
}

type MerchantInfo struct {
	MerchantId          string `json:"merchant_id"`          // 商户ID
	EntityName          string `json:"entity_name"`          // 商户主体名称
	BrandName           string `json:"brand_name"`           // 商户品牌名称
	WebsiteUrl          string `json:"website_url"`          // 商户官方网站
	MerchantLogo        string `json:"merchant_logo"`        // 商户官方logo URL
	MerchantCountry     string `json:"merchant_country"`     // 商户经营国家
	ContactName         string `json:"contact_name"`         // 商户主要联系人姓名
	ContactEmail        string `json:"contact_email"`        // 商户主要联系人邮箱
	ApiKey              string `json:"api_key"`              // API密钥
	VerifiedStatus      string `json:"verified_status"`      // 审核状态
	MerchantStatus      string `json:"merchant_status"`      // 商户状态
	BusinessDescription string `json:"business_description"` // 商户业务描述
	CreatedTime         string `json:"created_time"`         // 创建时间
	UpdatedTime         string `json:"updated_time"`         // 更新时间
}

type MerchantRegisterReq struct {
	EntityName          string `json:"entity_name" validate:"required"`         // 商户主体名称，公司名称
	BrandName           string `json:"brand_name" validate:"required"`          // 商户品牌名称
	WebsiteUrl          string `json:"website_url,optional"`                    // 商户官方网站
	MerchantLogo        string `json:"merchant_logo,optional"`                  // 商户官方logo URL
	MerchantCountry     string `json:"merchant_country" validate:"required"`    // 商户经营国家
	ContactName         string `json:"contact_name" validate:"required"`        // 商户主要联系人姓名
	ContactEmail        string `json:"contact_email" validate:"required,email"` // 商户主要联系人邮箱
	BusinessDescription string `json:"business_description,optional"`           // 商户业务描述
}

type MerchantRegisterResp struct {
	MerchantId     string `json:"merchant_id"`     // 系统生成的商户ID
	ApiKey         string `json:"api_key"`         // 系统生成的API密钥
	VerifiedStatus string `json:"verified_status"` // 审核状态
	MerchantStatus string `json:"merchant_status"` // 商户状态
	CreatedTime    string `json:"created_time"`    // 创建时间
}

type UpdateMerchantReq struct {
	MerchantId          string `json:"merchant_id" validate:"required"`         // 商户ID
	EntityName          string `json:"entity_name" validate:"required"`         // 商户主体名称
	BrandName           string `json:"brand_name" validate:"required"`          // 商户品牌名称
	WebsiteUrl          string `json:"website_url,optional"`                    // 商户官方网站
	MerchantLogo        string `json:"merchant_logo,optional"`                  // 商户官方logo URL
	MerchantCountry     string `json:"merchant_country" validate:"required"`    // 商户经营国家
	ContactName         string `json:"contact_name" validate:"required"`        // 商户主要联系人姓名
	ContactEmail        string `json:"contact_email" validate:"required,email"` // 商户主要联系人邮箱
	BusinessDescription string `json:"business_description,optional"`           // 商户业务描述
}

type UpdateMerchantResp struct {
	Merchant MerchantInfo `json:"merchant"` // 更新后的商户信息
}
