// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CardholderRegisterReq struct {
	Name string `json:"name"`
}

type CardholderRegisterResp struct {
	Id int64 `json:"id"`
}

type MerchantRegisterReq struct {
	Name string `json:"name"`
}

type MerchantRegisterResp struct {
	Id int64 `json:"id"`
}

type OpenCardReq struct {
	Name string `json:"name"`
}

type OpenCardResp struct {
	Id int64 `json:"id"`
}
