// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	merchant "pelago-card-backend/api/internal/handler/merchant"
	"pelago-card-backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取商户信息
				Method:  http.MethodGet,
				Path:    "/:merchant_id",
				Handler: merchant.GetMerchantHandler(serverCtx),
			},
			{
				// 商户列表查询
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: merchant.ListMerchantsHandler(serverCtx),
			},
			{
				// 商户入驻注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: merchant.MerchantRegisterHandler(serverCtx),
			},
			{
				// 更新商户信息
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: merchant.UpdateMerchantHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/merchant"),
	)
}
