// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: integration.proto

package server

import (
	"context"

	"pelago-card-backend/app/integration/internal/logic"
	"pelago-card-backend/app/integration/internal/svc"
	"pelago-card-backend/app/pb/integration"
)

type IntegrationServiceServer struct {
	svcCtx *svc.ServiceContext
	integration.UnimplementedIntegrationServiceServer
}

func NewIntegrationServiceServer(svcCtx *svc.ServiceContext) *IntegrationServiceServer {
	return &IntegrationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IntegrationServiceServer) Recharge(ctx context.Context, in *integration.RechargeReq) (*integration.RechargeResp, error) {
	l := logic.NewRechargeLogic(ctx, s.svcCtx)
	return l.Recharge(in)
}
