// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: integration.proto

package integrationservice

import (
	"context"

	"pelago-card-backend/app/pb/integration"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RechargeReq  = integration.RechargeReq
	RechargeResp = integration.RechargeResp

	IntegrationService interface {
		Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error)
	}

	defaultIntegrationService struct {
		cli zrpc.Client
	}
)

func NewIntegrationService(cli zrpc.Client) IntegrationService {
	return &defaultIntegrationService{
		cli: cli,
	}
}

func (m *defaultIntegrationService) Recharge(ctx context.Context, in *RechargeReq, opts ...grpc.CallOption) (*RechargeResp, error) {
	client := integration.NewIntegrationServiceClient(m.cli.Conn())
	return client.Recharge(ctx, in, opts...)
}
