// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/cardholder.proto

package cardholder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardHolderService_CreateAccount_FullMethodName = "/card.CardHolderService/CreateAccount"
)

// CardHolderServiceClient is the client API for CardHolderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardHolderServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountResp, error)
}

type cardHolderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCardHolderServiceClient(cc grpc.ClientConnInterface) CardHolderServiceClient {
	return &cardHolderServiceClient{cc}
}

func (c *cardHolderServiceClient) CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResp)
	err := c.cc.Invoke(ctx, CardHolderService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardHolderServiceServer is the server API for CardHolderService service.
// All implementations must embed UnimplementedCardHolderServiceServer
// for forward compatibility.
type CardHolderServiceServer interface {
	CreateAccount(context.Context, *CreateAccountReq) (*CreateAccountResp, error)
	mustEmbedUnimplementedCardHolderServiceServer()
}

// UnimplementedCardHolderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardHolderServiceServer struct{}

func (UnimplementedCardHolderServiceServer) CreateAccount(context.Context, *CreateAccountReq) (*CreateAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedCardHolderServiceServer) mustEmbedUnimplementedCardHolderServiceServer() {}
func (UnimplementedCardHolderServiceServer) testEmbeddedByValue()                           {}

// UnsafeCardHolderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardHolderServiceServer will
// result in compilation errors.
type UnsafeCardHolderServiceServer interface {
	mustEmbedUnimplementedCardHolderServiceServer()
}

func RegisterCardHolderServiceServer(s grpc.ServiceRegistrar, srv CardHolderServiceServer) {
	// If the following call pancis, it indicates UnimplementedCardHolderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardHolderService_ServiceDesc, srv)
}

func _CardHolderService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardHolderServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardHolderService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardHolderServiceServer).CreateAccount(ctx, req.(*CreateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CardHolderService_ServiceDesc is the grpc.ServiceDesc for CardHolderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardHolderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "card.CardHolderService",
	HandlerType: (*CardHolderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _CardHolderService_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cardholder.proto",
}
