// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/card.proto

package card

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商户注册请求
type RegisterMerchantReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EntityName          string                 `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`                            // 商户主体名称，公司名称
	BrandName           string                 `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`                               // 商户品牌名称
	WebsiteUrl          string                 `protobuf:"bytes,3,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`                            // 商户官方网站
	MerchantLogo        string                 `protobuf:"bytes,4,opt,name=merchant_logo,json=merchantLogo,proto3" json:"merchant_logo,omitempty"`                      // 商户官方logo URL
	MerchantCountry     string                 `protobuf:"bytes,5,opt,name=merchant_country,json=merchantCountry,proto3" json:"merchant_country,omitempty"`             // 商户经营国家
	ContactName         string                 `protobuf:"bytes,6,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`                         // 商户主要联系人姓名
	ContactEmail        string                 `protobuf:"bytes,7,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`                      // 商户主要联系人邮箱
	BusinessDescription string                 `protobuf:"bytes,8,opt,name=business_description,json=businessDescription,proto3" json:"business_description,omitempty"` // 商户业务描述(可选)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterMerchantReq) Reset() {
	*x = RegisterMerchantReq{}
	mi := &file_proto_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMerchantReq) ProtoMessage() {}

func (x *RegisterMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMerchantReq.ProtoReflect.Descriptor instead.
func (*RegisterMerchantReq) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMerchantReq) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *RegisterMerchantReq) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *RegisterMerchantReq) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *RegisterMerchantReq) GetMerchantLogo() string {
	if x != nil {
		return x.MerchantLogo
	}
	return ""
}

func (x *RegisterMerchantReq) GetMerchantCountry() string {
	if x != nil {
		return x.MerchantCountry
	}
	return ""
}

func (x *RegisterMerchantReq) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *RegisterMerchantReq) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *RegisterMerchantReq) GetBusinessDescription() string {
	if x != nil {
		return x.BusinessDescription
	}
	return ""
}

// 商户注册响应
type RegisterMerchantResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`             // 系统生成的商户ID
	ApiKey         string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                         // 系统生成的API密钥
	VerifiedStatus string                 `protobuf:"bytes,3,opt,name=verified_status,json=verifiedStatus,proto3" json:"verified_status,omitempty"` // 审核状态
	MerchantStatus string                 `protobuf:"bytes,4,opt,name=merchant_status,json=merchantStatus,proto3" json:"merchant_status,omitempty"` // 商户状态
	CreatedTime    string                 `protobuf:"bytes,5,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`          // 创建时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterMerchantResp) Reset() {
	*x = RegisterMerchantResp{}
	mi := &file_proto_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMerchantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMerchantResp) ProtoMessage() {}

func (x *RegisterMerchantResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMerchantResp.ProtoReflect.Descriptor instead.
func (*RegisterMerchantResp) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMerchantResp) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RegisterMerchantResp) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RegisterMerchantResp) GetVerifiedStatus() string {
	if x != nil {
		return x.VerifiedStatus
	}
	return ""
}

func (x *RegisterMerchantResp) GetMerchantStatus() string {
	if x != nil {
		return x.MerchantStatus
	}
	return ""
}

func (x *RegisterMerchantResp) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

// 获取商户信息请求
type GetMerchantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // 商户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantReq) Reset() {
	*x = GetMerchantReq{}
	mi := &file_proto_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantReq) ProtoMessage() {}

func (x *GetMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantReq.ProtoReflect.Descriptor instead.
func (*GetMerchantReq) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

// 商户信息
type MerchantInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MerchantId          string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`                             // 商户ID
	EntityName          string                 `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`                             // 商户主体名称
	BrandName           string                 `protobuf:"bytes,3,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`                                // 商户品牌名称
	WebsiteUrl          string                 `protobuf:"bytes,4,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`                             // 商户官方网站
	MerchantLogo        string                 `protobuf:"bytes,5,opt,name=merchant_logo,json=merchantLogo,proto3" json:"merchant_logo,omitempty"`                       // 商户官方logo URL
	MerchantCountry     string                 `protobuf:"bytes,6,opt,name=merchant_country,json=merchantCountry,proto3" json:"merchant_country,omitempty"`              // 商户经营国家
	ContactName         string                 `protobuf:"bytes,7,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`                          // 商户主要联系人姓名
	ContactEmail        string                 `protobuf:"bytes,8,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`                       // 商户主要联系人邮箱
	ApiKey              string                 `protobuf:"bytes,9,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                                         // API密钥
	VerifiedStatus      string                 `protobuf:"bytes,10,opt,name=verified_status,json=verifiedStatus,proto3" json:"verified_status,omitempty"`                // 审核状态
	MerchantStatus      string                 `protobuf:"bytes,11,opt,name=merchant_status,json=merchantStatus,proto3" json:"merchant_status,omitempty"`                // 商户状态
	BusinessDescription string                 `protobuf:"bytes,12,opt,name=business_description,json=businessDescription,proto3" json:"business_description,omitempty"` // 商户业务描述
	CreatedTime         string                 `protobuf:"bytes,13,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`                         // 创建时间
	UpdatedTime         string                 `protobuf:"bytes,14,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`                         // 更新时间
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MerchantInfo) Reset() {
	*x = MerchantInfo{}
	mi := &file_proto_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantInfo) ProtoMessage() {}

func (x *MerchantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantInfo.ProtoReflect.Descriptor instead.
func (*MerchantInfo) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{3}
}

func (x *MerchantInfo) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantInfo) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *MerchantInfo) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *MerchantInfo) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *MerchantInfo) GetMerchantLogo() string {
	if x != nil {
		return x.MerchantLogo
	}
	return ""
}

func (x *MerchantInfo) GetMerchantCountry() string {
	if x != nil {
		return x.MerchantCountry
	}
	return ""
}

func (x *MerchantInfo) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *MerchantInfo) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *MerchantInfo) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *MerchantInfo) GetVerifiedStatus() string {
	if x != nil {
		return x.VerifiedStatus
	}
	return ""
}

func (x *MerchantInfo) GetMerchantStatus() string {
	if x != nil {
		return x.MerchantStatus
	}
	return ""
}

func (x *MerchantInfo) GetBusinessDescription() string {
	if x != nil {
		return x.BusinessDescription
	}
	return ""
}

func (x *MerchantInfo) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *MerchantInfo) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

// 获取商户信息响应
type GetMerchantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantInfo          `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"` // 商户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResp) Reset() {
	*x = GetMerchantResp{}
	mi := &file_proto_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResp) ProtoMessage() {}

func (x *GetMerchantResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResp.ProtoReflect.Descriptor instead.
func (*GetMerchantResp) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{4}
}

func (x *GetMerchantResp) GetMerchant() *MerchantInfo {
	if x != nil {
		return x.Merchant
	}
	return nil
}

// 更新商户信息请求
type UpdateMerchantReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MerchantId          string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`                            // 商户ID
	EntityName          string                 `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`                            // 商户主体名称
	BrandName           string                 `protobuf:"bytes,3,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`                               // 商户品牌名称
	WebsiteUrl          string                 `protobuf:"bytes,4,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`                            // 商户官方网站
	MerchantLogo        string                 `protobuf:"bytes,5,opt,name=merchant_logo,json=merchantLogo,proto3" json:"merchant_logo,omitempty"`                      // 商户官方logo URL
	MerchantCountry     string                 `protobuf:"bytes,6,opt,name=merchant_country,json=merchantCountry,proto3" json:"merchant_country,omitempty"`             // 商户经营国家
	ContactName         string                 `protobuf:"bytes,7,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`                         // 商户主要联系人姓名
	ContactEmail        string                 `protobuf:"bytes,8,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`                      // 商户主要联系人邮箱
	BusinessDescription string                 `protobuf:"bytes,9,opt,name=business_description,json=businessDescription,proto3" json:"business_description,omitempty"` // 商户业务描述
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateMerchantReq) Reset() {
	*x = UpdateMerchantReq{}
	mi := &file_proto_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantReq) ProtoMessage() {}

func (x *UpdateMerchantReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantReq.ProtoReflect.Descriptor instead.
func (*UpdateMerchantReq) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMerchantReq) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMerchantReq) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *UpdateMerchantReq) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *UpdateMerchantReq) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *UpdateMerchantReq) GetMerchantLogo() string {
	if x != nil {
		return x.MerchantLogo
	}
	return ""
}

func (x *UpdateMerchantReq) GetMerchantCountry() string {
	if x != nil {
		return x.MerchantCountry
	}
	return ""
}

func (x *UpdateMerchantReq) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *UpdateMerchantReq) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *UpdateMerchantReq) GetBusinessDescription() string {
	if x != nil {
		return x.BusinessDescription
	}
	return ""
}

// 更新商户信息响应
type UpdateMerchantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantInfo          `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"` // 更新后的商户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantResp) Reset() {
	*x = UpdateMerchantResp{}
	mi := &file_proto_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantResp) ProtoMessage() {}

func (x *UpdateMerchantResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantResp.ProtoReflect.Descriptor instead.
func (*UpdateMerchantResp) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMerchantResp) GetMerchant() *MerchantInfo {
	if x != nil {
		return x.Merchant
	}
	return nil
}

// 商户列表查询请求
type ListMerchantsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                          // 页码，从1开始
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                  // 每页大小
	VerifiedStatus string                 `protobuf:"bytes,3,opt,name=verified_status,json=verifiedStatus,proto3" json:"verified_status,omitempty"` // 筛选审核状态(可选)
	MerchantStatus string                 `protobuf:"bytes,4,opt,name=merchant_status,json=merchantStatus,proto3" json:"merchant_status,omitempty"` // 筛选商户状态(可选)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMerchantsReq) Reset() {
	*x = ListMerchantsReq{}
	mi := &file_proto_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsReq) ProtoMessage() {}

func (x *ListMerchantsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsReq.ProtoReflect.Descriptor instead.
func (*ListMerchantsReq) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{7}
}

func (x *ListMerchantsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMerchantsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMerchantsReq) GetVerifiedStatus() string {
	if x != nil {
		return x.VerifiedStatus
	}
	return ""
}

func (x *ListMerchantsReq) GetMerchantStatus() string {
	if x != nil {
		return x.MerchantStatus
	}
	return ""
}

// 商户列表查询响应
type ListMerchantsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchants     []*MerchantInfo        `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`                // 商户列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数量
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResp) Reset() {
	*x = ListMerchantsResp{}
	mi := &file_proto_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResp) ProtoMessage() {}

func (x *ListMerchantsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResp.ProtoReflect.Descriptor instead.
func (*ListMerchantsResp) Descriptor() ([]byte, []int) {
	return file_proto_card_proto_rawDescGZIP(), []int{8}
}

func (x *ListMerchantsResp) GetMerchants() []*MerchantInfo {
	if x != nil {
		return x.Merchants
	}
	return nil
}

func (x *ListMerchantsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMerchantsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMerchantsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_proto_card_proto protoreflect.FileDescriptor

const file_proto_card_proto_rawDesc = "" +
	"\n" +
	"\x10proto/card.proto\x12\x04card\"\xc1\x02\n" +
	"\x13RegisterMerchantReq\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x02 \x01(\tR\tbrandName\x12\x1f\n" +
	"\vwebsite_url\x18\x03 \x01(\tR\n" +
	"websiteUrl\x12#\n" +
	"\rmerchant_logo\x18\x04 \x01(\tR\fmerchantLogo\x12)\n" +
	"\x10merchant_country\x18\x05 \x01(\tR\x0fmerchantCountry\x12!\n" +
	"\fcontact_name\x18\x06 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_email\x18\a \x01(\tR\fcontactEmail\x121\n" +
	"\x14business_description\x18\b \x01(\tR\x13businessDescription\"\xc5\x01\n" +
	"\x14RegisterMerchantResp\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12'\n" +
	"\x0fverified_status\x18\x03 \x01(\tR\x0everifiedStatus\x12'\n" +
	"\x0fmerchant_status\x18\x04 \x01(\tR\x0emerchantStatus\x12!\n" +
	"\fcreated_time\x18\x05 \x01(\tR\vcreatedTime\"1\n" +
	"\x0eGetMerchantReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\x8c\x04\n" +
	"\fMerchantInfo\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\ventity_name\x18\x02 \x01(\tR\n" +
	"entityName\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x03 \x01(\tR\tbrandName\x12\x1f\n" +
	"\vwebsite_url\x18\x04 \x01(\tR\n" +
	"websiteUrl\x12#\n" +
	"\rmerchant_logo\x18\x05 \x01(\tR\fmerchantLogo\x12)\n" +
	"\x10merchant_country\x18\x06 \x01(\tR\x0fmerchantCountry\x12!\n" +
	"\fcontact_name\x18\a \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_email\x18\b \x01(\tR\fcontactEmail\x12\x17\n" +
	"\aapi_key\x18\t \x01(\tR\x06apiKey\x12'\n" +
	"\x0fverified_status\x18\n" +
	" \x01(\tR\x0everifiedStatus\x12'\n" +
	"\x0fmerchant_status\x18\v \x01(\tR\x0emerchantStatus\x121\n" +
	"\x14business_description\x18\f \x01(\tR\x13businessDescription\x12!\n" +
	"\fcreated_time\x18\r \x01(\tR\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\x0e \x01(\tR\vupdatedTime\"A\n" +
	"\x0fGetMerchantResp\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.card.MerchantInfoR\bmerchant\"\xe0\x02\n" +
	"\x11UpdateMerchantReq\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\ventity_name\x18\x02 \x01(\tR\n" +
	"entityName\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x03 \x01(\tR\tbrandName\x12\x1f\n" +
	"\vwebsite_url\x18\x04 \x01(\tR\n" +
	"websiteUrl\x12#\n" +
	"\rmerchant_logo\x18\x05 \x01(\tR\fmerchantLogo\x12)\n" +
	"\x10merchant_country\x18\x06 \x01(\tR\x0fmerchantCountry\x12!\n" +
	"\fcontact_name\x18\a \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_email\x18\b \x01(\tR\fcontactEmail\x121\n" +
	"\x14business_description\x18\t \x01(\tR\x13businessDescription\"D\n" +
	"\x12UpdateMerchantResp\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.card.MerchantInfoR\bmerchant\"\x95\x01\n" +
	"\x10ListMerchantsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12'\n" +
	"\x0fverified_status\x18\x03 \x01(\tR\x0everifiedStatus\x12'\n" +
	"\x0fmerchant_status\x18\x04 \x01(\tR\x0emerchantStatus\"\x8c\x01\n" +
	"\x11ListMerchantsResp\x120\n" +
	"\tmerchants\x18\x01 \x03(\v2\x12.card.MerchantInfoR\tmerchants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\x9b\x02\n" +
	"\vCardService\x12I\n" +
	"\x10RegisterMerchant\x12\x19.card.RegisterMerchantReq\x1a\x1a.card.RegisterMerchantResp\x12:\n" +
	"\vGetMerchant\x12\x14.card.GetMerchantReq\x1a\x15.card.GetMerchantResp\x12C\n" +
	"\x0eUpdateMerchant\x12\x17.card.UpdateMerchantReq\x1a\x18.card.UpdateMerchantResp\x12@\n" +
	"\rListMerchants\x12\x16.card.ListMerchantsReq\x1a\x17.card.ListMerchantsRespB\bZ\x06./cardb\x06proto3"

var (
	file_proto_card_proto_rawDescOnce sync.Once
	file_proto_card_proto_rawDescData []byte
)

func file_proto_card_proto_rawDescGZIP() []byte {
	file_proto_card_proto_rawDescOnce.Do(func() {
		file_proto_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_card_proto_rawDesc), len(file_proto_card_proto_rawDesc)))
	})
	return file_proto_card_proto_rawDescData
}

var file_proto_card_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_card_proto_goTypes = []any{
	(*RegisterMerchantReq)(nil),  // 0: card.RegisterMerchantReq
	(*RegisterMerchantResp)(nil), // 1: card.RegisterMerchantResp
	(*GetMerchantReq)(nil),       // 2: card.GetMerchantReq
	(*MerchantInfo)(nil),         // 3: card.MerchantInfo
	(*GetMerchantResp)(nil),      // 4: card.GetMerchantResp
	(*UpdateMerchantReq)(nil),    // 5: card.UpdateMerchantReq
	(*UpdateMerchantResp)(nil),   // 6: card.UpdateMerchantResp
	(*ListMerchantsReq)(nil),     // 7: card.ListMerchantsReq
	(*ListMerchantsResp)(nil),    // 8: card.ListMerchantsResp
}
var file_proto_card_proto_depIdxs = []int32{
	3, // 0: card.GetMerchantResp.merchant:type_name -> card.MerchantInfo
	3, // 1: card.UpdateMerchantResp.merchant:type_name -> card.MerchantInfo
	3, // 2: card.ListMerchantsResp.merchants:type_name -> card.MerchantInfo
	0, // 3: card.CardService.RegisterMerchant:input_type -> card.RegisterMerchantReq
	2, // 4: card.CardService.GetMerchant:input_type -> card.GetMerchantReq
	5, // 5: card.CardService.UpdateMerchant:input_type -> card.UpdateMerchantReq
	7, // 6: card.CardService.ListMerchants:input_type -> card.ListMerchantsReq
	1, // 7: card.CardService.RegisterMerchant:output_type -> card.RegisterMerchantResp
	4, // 8: card.CardService.GetMerchant:output_type -> card.GetMerchantResp
	6, // 9: card.CardService.UpdateMerchant:output_type -> card.UpdateMerchantResp
	8, // 10: card.CardService.ListMerchants:output_type -> card.ListMerchantsResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_card_proto_init() }
func file_proto_card_proto_init() {
	if File_proto_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_card_proto_rawDesc), len(file_proto_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_card_proto_goTypes,
		DependencyIndexes: file_proto_card_proto_depIdxs,
		MessageInfos:      file_proto_card_proto_msgTypes,
	}.Build()
	File_proto_card_proto = out.File
	file_proto_card_proto_goTypes = nil
	file_proto_card_proto_depIdxs = nil
}
