// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/integration.proto

package integration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RechargeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeReq) Reset() {
	*x = RechargeReq{}
	mi := &file_proto_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeReq) ProtoMessage() {}

func (x *RechargeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeReq.ProtoReflect.Descriptor instead.
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return file_proto_integration_proto_rawDescGZIP(), []int{0}
}

type RechargeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeResp) Reset() {
	*x = RechargeResp{}
	mi := &file_proto_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeResp) ProtoMessage() {}

func (x *RechargeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeResp.ProtoReflect.Descriptor instead.
func (*RechargeResp) Descriptor() ([]byte, []int) {
	return file_proto_integration_proto_rawDescGZIP(), []int{1}
}

var File_proto_integration_proto protoreflect.FileDescriptor

const file_proto_integration_proto_rawDesc = "" +
	"\n" +
	"\x17proto/integration.proto\x12\x04card\"\r\n" +
	"\vRechargeReq\"\x0e\n" +
	"\fRechargeResp2G\n" +
	"\x12IntegrationService\x121\n" +
	"\bRecharge\x12\x11.card.RechargeReq\x1a\x12.card.RechargeRespB\x0fZ\r./integrationb\x06proto3"

var (
	file_proto_integration_proto_rawDescOnce sync.Once
	file_proto_integration_proto_rawDescData []byte
)

func file_proto_integration_proto_rawDescGZIP() []byte {
	file_proto_integration_proto_rawDescOnce.Do(func() {
		file_proto_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_integration_proto_rawDesc), len(file_proto_integration_proto_rawDesc)))
	})
	return file_proto_integration_proto_rawDescData
}

var file_proto_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_integration_proto_goTypes = []any{
	(*RechargeReq)(nil),  // 0: card.RechargeReq
	(*RechargeResp)(nil), // 1: card.RechargeResp
}
var file_proto_integration_proto_depIdxs = []int32{
	0, // 0: card.IntegrationService.Recharge:input_type -> card.RechargeReq
	1, // 1: card.IntegrationService.Recharge:output_type -> card.RechargeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_integration_proto_init() }
func file_proto_integration_proto_init() {
	if File_proto_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_integration_proto_rawDesc), len(file_proto_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_integration_proto_goTypes,
		DependencyIndexes: file_proto_integration_proto_depIdxs,
		MessageInfos:      file_proto_integration_proto_msgTypes,
	}.Build()
	File_proto_integration_proto = out.File
	file_proto_integration_proto_goTypes = nil
	file_proto_integration_proto_depIdxs = nil
}
