// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: merchant.proto

package merchantservice

import (
	"context"

	"pelago-card-backend/app/pb/merchant"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RegisterMerchantReq  = merchant.RegisterMerchantReq
	RegisterMerchantResp = merchant.RegisterMerchantResp

	MerchantService interface {
		RegisterMerchant(ctx context.Context, in *RegisterMerchantReq, opts ...grpc.CallOption) (*RegisterMerchantResp, error)
	}

	defaultMerchantService struct {
		cli zrpc.Client
	}
)

func NewMerchantService(cli zrpc.Client) MerchantService {
	return &defaultMerchantService{
		cli: cli,
	}
}

func (m *defaultMerchantService) RegisterMerchant(ctx context.Context, in *RegisterMerchantReq, opts ...grpc.CallOption) (*RegisterMerchantResp, error) {
	client := merchant.NewMerchantServiceClient(m.cli.Conn())
	return client.RegisterMerchant(ctx, in, opts...)
}
