// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: card.proto

package server

import (
	"context"

	"pelago-card-backend/app/card/internal/logic"
	"pelago-card-backend/app/card/internal/svc"
	"pelago-card-backend/app/pb/card"
)

type CardServiceServer struct {
	svcCtx *svc.ServiceContext
	card.UnimplementedCardServiceServer
}

func NewCardServiceServer(svcCtx *svc.ServiceContext) *CardServiceServer {
	return &CardServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CardServiceServer) OpenCard(ctx context.Context, in *card.OpenCardReq) (*card.OpenCardResp, error) {
	l := logic.NewOpenCardLogic(ctx, s.svcCtx)
	return l.OpenCard(in)
}
