// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: cardholder.proto

package cardholderservice

import (
	"context"

	"pelago-card-backend/app/pb/cardholder"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAccountReq  = cardholder.CreateAccountReq
	CreateAccountResp = cardholder.CreateAccountResp

	CardHolderService interface {
		CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountResp, error)
	}

	defaultCardHolderService struct {
		cli zrpc.Client
	}
)

func NewCardHolderService(cli zrpc.Client) CardHolderService {
	return &defaultCardHolderService{
		cli: cli,
	}
}

func (m *defaultCardHolderService) CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountResp, error) {
	client := cardholder.NewCardHolderServiceClient(m.cli.Conn())
	return client.CreateAccount(ctx, in, opts...)
}
